-- Vanilla EnchantStatsDB
EnchantStatsDB = {
    -- Back / Cloak
    ["Enchant Cloak - Minor Protection"] = "+10 armor",
    ["Enchant Cloak - Lesser Protection"] = "+20 armor",
    ["Enchant Cloak - Defense"] = "+30 armor",
    ["Enchant Cloak - Greater Defense"] = "+50 armor",
    ["Enchant Cloak - Superior Defense"] = "+70 armor",
    ["Enchant Cloak - Dodge"] = "+1% dodge rating",
    ["Enchant Cloak - Stealth"] = "+5 stealth rating",
    ["Enchant Cloak - Subtlety"] = "-2% threat",
    ["Enchant Cloak - Minor Resistance"] = "+1 all resistances",
    ["Enchant Cloak - Lesser Fire Resistance"] = "+5 fire resistance",
    ["Enchant Cloak - Fire Resistance"] = "+7 fire resistance",
    ["Enchant Cloak - Greater Fire Resistance"] = "+15 fire resistance",
    ["Enchant Cloak - Lesser Shadow Resistance"] = "+10 shadow resistance",
    ["Enchant Cloak - Resistance"] = "+3 all resistances",
    ["Enchant Cloak - Greater Resistance"] = "+5 all resistances",
    ["Enchant Cloak - Lesser Agility"] = "+3 agility",
    ["Enchant Cloak - Minor Agility"] = "+1 agility",

    -- Chest
    ["Enchant Chest - Minor Health"] = "+5 health",
    ["Enchant Chest - Lesser Health"] = "+15 health",
    ["Enchant Chest - Health"] = "+25 health",
    ["Enchant Chest - Greater Health"] = "+35 health",
    ["Enchant Chest - Superior Health"] = "+50 health",
    ["Enchant Chest - Major Health"] = "+100 health",
    ["Enchant Chest - Minor Mana"] = "+5 mana",
    ["Enchant Chest - Lesser Mana"] = "+20 mana",
    ["Enchant Chest - Mana"] = "+30 mana",
    ["Enchant Chest - Greater Mana"] = "+50 mana",
    ["Enchant Chest - Superior Mana"] = "+65 mana",
    ["Enchant Chest - Major Mana"] = "+100 mana",
    ["Enchant Chest - Minor Absorption"] = "2% chance to absorb 10 damage",
    ["Enchant Chest - Lesser Absorption"] = "5% chance to absorb 25 damage",
    ["Enchant Chest - Stats"] = "+3 all stats",
    ["Enchant Chest - Lesser Stats"] = "+2 all stats",
    ["Enchant Chest - Minor Stats"] = "+1 all stats",
    ["Enchant Chest - Greater Stats"] = "+4 all stats",

    -- Wrist / Bracer
    ["Enchant Bracer - Minor Health"] = "+5 health",
    ["Enchant Bracer - Minor Deflection"] = "+1 defense rating",
    ["Enchant Bracer - Lesser Deflection"] = "+2 defense rating",
    ["Enchant Bracer - Deflection"] = "+3 defense rating",
    ["Enchant Bracer - Minor Agility"] = "+1 agility",
    ["Enchant Bracer - Lesser Agility"] = "+3 agility",
    ["Enchant Bracer - Minor Strength"] = "+1 strength",
    ["Enchant Bracer - Lesser Strength"] = "+3 strength",
    ["Enchant Bracer - Strength"] = "+5 strength",
    ["Enchant Bracer - Greater Strength"] = "+7 strength",
    ["Enchant Bracer - Superior Strength"] = "+9 strength",
    ["Enchant Bracer - Minor Stamina"] = "+1 stamina",
    ["Enchant Bracer - Lesser Stamina"] = "+3 stamina",
    ["Enchant Bracer - Stamina"] = "+5 stamina",
    ["Enchant Bracer - Greater Stamina"] = "+7 stamina",
    ["Enchant Bracer - Superior Stamina"] = "+9 stamina",
    ["Enchant Bracer - Minor Spirit"] = "+1 spirit",
    ["Enchant Bracer - Lesser Spirit"] = "+3 spirit",
    ["Enchant Bracer - Spirit"] = "+5 spirit",
    ["Enchant Bracer - Greater Spirit"] = "+7 spirit",
    ["Enchant Bracer - Superior Spirit"] = "+9 spirit",
    ["Enchant Bracer - Mana Regeneration"] = "+4 mana/5 sec",
    ["Enchant Bracer - Healing Power"] = "+24 healing",

    -- Hands / Gloves
    ["Enchant Gloves - Minor Haste"] = "+1% attack speed bonus",
    ["Enchant Gloves - Strength"] = "+5 strength",
    ["Enchant Gloves - Greater Strength"] = "+7 strength",
    ["Enchant Gloves - Agility"] = "+5 agility",
    ["Enchant Gloves - Greater Agility"] = "+7 agility",
    ["Enchant Gloves - Superior Agility"] = "+15 agility",
    ["Enchant Gloves - Healing Power"] = "+55 healing",
    ["Enchant Gloves - Fire Power"] = "+20 fire spell damage",
    ["Enchant Gloves - Frost Power"] = "+20 frost spell damage",
    ["Enchant Gloves - Shadow Power"] = "+20 shadow spell damage",
    ["Enchant Gloves - Threat"] = "+2% threat",
    ["Enchant Gloves - Fishing"] = "+2 fishing",
    ["Enchant Gloves - Herbalism"] = "+2 herbalism",
    ["Enchant Gloves - Advanced Herbalism"] = "+5 herbalism",
    ["Enchant Gloves - Mining"] = "+2 mining",
    ["Enchant Gloves - Advanced Mining"] = "+5 mining",
    ["Enchant Gloves - Skinning"] = "+5 skinning",
    ["Enchant Gloves - Riding Skill"] = "+2% mounted speed",

    -- Legs
    ["Lesser Arcanum of Tenacity"] = "+125 armor",
    ["Arcanum of Focus"] = "+8 spell damage and healing",
    ["Arcanum of Rapidity"] = "+1% haste rating",
    ["Arcanum of Protection"] = "+1% dodge rating",
    ["Lesser Arcanum of Constitution"] = "+100 health",
    ["Lesser Arcanum of Rumination"] = "+150 mana",
    ["Core Armor Kit"] = "+3 defense rating",
    ["Lesser Arcanum of Resilience"] = "+20 fire resistance",
    ["Ice Guard"] = "+10 frost resistance",
    ["Savage Guard"] = "+10 nature resistance",
    ["Shadow Guard"] = "+10 shadow resistance",
    ["Lesser Arcanum of Voracity"] = "+8 to all stats (agility/intellect/spirit/stamina/strength)",

    -- Feet / Boots
    ["Enchant Boots - Minor Agility"] = "+1 agility",
    ["Enchant Boots - Lesser Agility"] = "+3 agility",
    ["Enchant Boots - Agility"] = "+5 agility",
    ["Enchant Boots - Greater Agility"] = "+7 agility",
    ["Enchant Boots - Minor Stamina"] = "+1 stamina",
    ["Enchant Boots - Lesser Stamina"] = "+3 stamina",
    ["Enchant Boots - Stamina"] = "+5 stamina",
    ["Enchant Boots - Greater Stamina"] = "+7 stamina",
    ["Enchant Boots - Spirit"] = "+5 spirit",
    ["Enchant Boots - Lesser Spirit"] = "+3 spirit",
    ["Enchant Boots - Minor Speed"] = "+8% run speed",
    ["Mithril Spurs"] = "+4% mounted speed",

    -- Shoulders
    ["Zandalar Signet of Might"] = "+30 attack power",
    ["Zandalar Signet of Serenity"] = "+33 healing",
    ["Zandalar Signet of Mojo"] = "+18 spell damage and healing",
    ["Might of the Scourge"] = "+26 attack power, +1% critical strike rating",
    ["Power of the Scourge"] = "+15 spell damage and healing, +1% spell critical strike rating",
    ["Resilience of the Scourge"] = "+31 healing, +11 spell damage, +5 mana/5 sec",
    ["Fortitude of the Scourge"] = "+16 stamina, +100 armor",
    ["Chromatic Mantle of the Dawn"] = "+5 all resistances",
    ["Arcane Mantle of the Dawn"] = "+5 arcane resistance",
    ["Flame Mantle of the Dawn"] = "+5 fire resistance",
    ["Frost Mantle of the Dawn"] = "+5 frost resistance",
    ["Nature Mantle of the Dawn"] = "+5 nature resistance",
    ["Shadow Mantle of the Dawn"] = "+5 shadow resistance",

    -- Shield
    ["Enchant Shield - Minor Stamina"] = "+1 stamina",
    ["Enchant Shield - Lesser Stamina"] = "+3 stamina",
    ["Enchant Shield - Stamina"] = "+5 stamina",
    ["Enchant Shield - Greater Stamina"] = "+7 stamina",
    ["Enchant Shield - Minor Spirit"] = "+1 spirit",
    ["Enchant Shield - Lesser Spirit"] = "+3 spirit",
    ["Enchant Shield - Spirit"] = "+5 spirit",
    ["Enchant Shield - Greater Spirit"] = "+7 spirit",
    ["Enchant Shield - Superior Spirit"] = "+9 spirit",
    ["Enchant Shield - Frost Resistance"] = "+8 frost resistance",
    ["Enchant Shield - Lesser Block"] = "+2% block rating",

    -- Weapons / Melee
    ["Enchant Weapon - Minor Striking"] = "+1 damage",
    ["Enchant Weapon - Lesser Striking"] = "+2 damage",
    ["Enchant Weapon - Striking"] = "+3 damage",
    ["Enchant Weapon - Greater Striking"] = "+4 damage",
    ["Enchant Weapon - Superior Striking"] = "+5 damage",
    ["Enchant Weapon - Minor Beastslayer"] = "+2 damage to beasts",
    ["Enchant Weapon - Lesser Beastslayer"] = "+6 damage to beasts",
    ["Enchant Weapon - Lesser Elemental Slayer"] = "+6 damage to elementals",
    ["Enchant Weapon - Crusader"] = "Chance to heal 75-125 and adds +100 strength for 15 sec",
    ["Enchant Weapon - Demonslaying"] = "Chance to deal 75-125 holy damage to demons and stun 5 sec",
    ["Enchant Weapon - Fiery Weapon"] = "Often adds +40 fire damage",
    ["Enchant Weapon - Icy Chill"] = "Slows target movement 30%, increases time between attacks 25% for 5 sec",
    ["Enchant Weapon - Lifestealing"] = "Steals 30 health on hit",
    ["Enchant Weapon - Unholy Weapon"] = "Curses target, reduces damage by 15 for 12 sec",
    ["Enchant Weapon - Healing Power"] = "+55 healing",
    ["Enchant Weapon - Spell Power"] = "+30 spell damage and healing",
    ["Enchant Weapon - Winter's Might"] = "+7 frost spell damage",
    ["Steel Weapon Chain"] = "Cannot be disarmed",
    ["Enchant Weapon - Agility"] = "+15 agility",
    ["Enchant Weapon - Mighty Intellect"] = "+22 intellect",
    ["Enchant Weapon - Mighty Spirit"] = "+20 spirit",
    ["Enchant Weapon - Strength"] = "+15 strength",

    -- 2H Weapons
    ["Enchant 2H Weapon - Minor Impact"] = "+2 damage",
    ["Enchant 2H Weapon - Lesser Impact"] = "+3 damage",
    ["Enchant 2H Weapon - Impact"] = "+5 damage",
    ["Enchant 2H Weapon - Greater Impact"] = "+7 damage",
    ["Enchant 2H Weapon - Superior Impact"] = "+9 damage",
    ["Enchant 2H Weapon - Agility"] = "+25 agility",
    ["Enchant 2H Weapon - Lesser Intellect"] = "+3 intellect",
    ["Enchant 2H Weapon - Major Intellect"] = "+9 intellect",
    ["Enchant 2H Weapon - Lesser Spirit"] = "+3 spirit",
    ["Enchant 2H Weapon - Major Spirit"] = "+9 spirit",

    -- Ranged
    ["Biznicks 247x128 Accurascope"] = "+3% ranged hit rating",
    ["Sniper Scope"] = "+7 damage",
    ["Deadly Scope"] = "+5 damage",
    ["Accurate Scope"] = "+3 damage",
    ["Standard Scope"] = "+2 damage",
    ["Crude Scope"] = "+1 damage",

    -- Fishing Pole
    ["High Test Eternium Fishing Line"] = "+5 fishing",

    -- Class-specific / Arcanums
    ["Animist's Caress"] = "Druid +10 intellect, +10 stamina, +24 healing",
    ["Falcon's Call"] = "Hunter +10 stamina, +1% hit rating, +24 ranged attack power",
    ["Presence of Sight"] = "Mage +1% spell hit rating, +18 spell damage and healing",
    ["Syncretist's Sigil"] = "Paladin +10 stamina, +7 defense rating, +24 healing",
    ["Prophetic Aura"] = "Priest +10 stamina, +24 healing, +4 mana/5 sec",
    ["Death's Embrace"] = "Rogue +1% dodge rating, +28 attack power",
    ["Vodouisant's Vigilant Embrace"] = "Shaman +15 intellect, +13 spell damage and healing",
    ["Hoodoo Hex"] = "Warlock +10 stamina, +18 spell damage and healing",
    ["Presence of Might"] = "Warrior +10 stamina, +7 defense rating, +15 shield block value",
}
